# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  # you may remove this if you don't use vgo
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "docker.io/vshn/waf-tuning-tool:v{{ .Version }}"
  - "docker.io/vshn/waf-tuning-tool:v{{ .Major }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'

release:
  github:
    owner: vshn
    name: waf-tuning-tool
